server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coworking_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.coworking: DEBUG